lint:
  files_exist:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-scrna_logo_light.png
    - docs/images/nf-core-scrna_logo_light.png
    - docs/images/nf-core-scrna_logo_dark.png
    - docs/output.md
    - docs/README.md
    - .github/ISSUE_TEMPLATE/config.yml
    - .github/workflows/awstest.yml
    - .github/workflows/awsfulltest.yml
    - .github/workflows/linting_comment.yml
    - conf/igenomes.config
    - .editorconfig
  files_unchanged:
    - CODE_OF_CONDUCT.md
    - assets/nf-core-scrna_logo_light.png
    - docs/images/nf-core-scrna_logo_light.png
    - docs/images/nf-core-scrna_logo_dark.png
    - .github/ISSUE_TEMPLATE/bug_report.yml
    - .github/workflows/linting.yml
  multiqc_config:
    - report_comment
  nextflow_config:
    - manifest.name
    - manifest.homePage
  readme:
    - nextflow_badge
repository_type: pipeline
template:
  author: zhouyiqi
  description: single cell RNASeq nextflow pipeline
  name: scrna
  prefix: singleron-RD
  skip:
    - github_badges
    - igenomes
